document.write("<style>");
        document.write("* {");
        document.write("  box-sizing: border-box;");
        document.write("  font-family: Arial, Helvetica, sans-serif;");
        document.write("}");
        document.write("");
        document.write("ul {");
        document.write("  list-style-type: none;");
        document.write("  margin: 0;");
        document.write("  padding: 0;");
        document.write("  \/* width: 200px; *\/");
        document.write("  background-color: #f1f1f1;");
        document.write("}");
        document.write("");
        document.write("li a {");
        document.write("  display: block;");
        document.write("  color: #000;");
        document.write("  padding: 8px 16px;");
        document.write("  text-decoration: none;");
        document.write("}");
        document.write("");
        document.write("\/* Change the link color on hover *\/");
        document.write("li a:hover {");
        document.write("  background-color: #555;");
        document.write("  color: white;");
        document.write("}");
        document.write("");
        document.write("body {");
        document.write("  margin: 0;");
        document.write("  font-family: Arial, Helvetica, sans-serif;");
        document.write("}");
        document.write("");
        document.write("\/* Create two columns\/boxes that floats next to each other *\/");
        document.write("nav {");
        document.write("    float: left;");
        document.write("    width: 30%;");
        document.write("    \/* height: 900px;  only for demonstration, should be removed *\/");
        document.write("    background: rgb(255, 255, 255);");
        document.write("    padding: 20px;");
        document.write("}");
        document.write("");
        document.write("");
        document.write("\/* Style the list inside the menu *\/");
        document.write("nav ul {");
        document.write("    list-style-type: none;");
        document.write("    padding: 0;");
        document.write("}");
        document.write("");
        document.write("article {");
        document.write("    float: left;");
        document.write("    padding: 20px;");
        document.write("    width: 70%;");
        document.write("    background-color: #f1f1f1;");
        document.write("   \/*  height: 900px; only for demonstration, should be removed *\/");
        document.write("}");
        document.write("");
        document.write("");
        document.write("\/* Clear floats after the columns *\/");
        document.write("section:after {");
        document.write("    content: \"\";");
        document.write("    display: table;");
        document.write("    clear: both;");
        document.write("}");
        document.write("");
        document.write("\/* Style the footer *\/");
        document.write("");
        document.write("");
        document.write("@media (max-width: 600px) {");
        document.write("    nav, article {");
        document.write("        width: 100%;");
        document.write("        height: auto;");
        document.write("    }");
        document.write("}");
        document.write("");
        document.write("header {");
        document.write("    background-color: rgb(255, 94, 0);");
        document.write("    padding: 5px;");
        document.write("    text-align: center;");
        document.write("    font-size: 25px;");
        document.write("    color: white;");
        document.write("}");
        document.write("\/* .footer {");
        document.write("   position: fixed;");
        document.write("   left: 0;");
        document.write("   bottom: 0;");
        document.write("   width: 100%;");
        document.write("   background-color: white;");
        document.write("   color: black;");
        document.write("   text-align: center;");
        document.write("} *\/");
        document.write("");
        document.write("\/* Style the top navigation bar *\/");
        document.write(".topnav {");
        document.write("  overflow: hidden;");
        document.write("  background-color: #333;");
        document.write("}");
        document.write("");
        document.write("\/* Style the topnav links *\/");
        document.write(".topnav a {");
        document.write("  float: left;");
        document.write("  display: block;");
        document.write("  color: #f2f2f2;");
        document.write("  text-align: center;");
        document.write("  padding: 14px 16px;");
        document.write("  text-decoration: none;");
        document.write("}");
        document.write("");
        document.write("\/* Change color on hover *\/");
        document.write(".topnav a:hover {");
        document.write("  background-color: red;");
        document.write("  color: black;");
        document.write("}");
        document.write("");
        document.write("\/* Style the content *\/");
        document.write(".content {");
        document.write("  background-color: #ddd;");
        document.write("  padding: 10px;");
        document.write("  height: 200px; \/* Should be removed. Only for demonstration *\/");
        document.write("}");
        document.write("");
        document.write(".dropdown {");
        document.write("  float: left;");
        document.write("  overflow: hidden;");
        document.write("}");
        document.write("");
        document.write(".dropdown .dropbtn {");
        document.write("  font-size: 16px;  ");
        document.write("  border: none;");
        document.write("  outline: none;");
        document.write("  color: white;");
        document.write("  padding: 14px 16px;");
        document.write("  background-color: inherit;");
        document.write("  font-family: inherit;");
        document.write("  margin: 0;");
        document.write("}");
        document.write("");
        document.write(".navbar a:hover, .dropdown:hover .dropbtn {");
        document.write("  background-color: red;");
        document.write("}");
        document.write("");
        document.write(".dropdown-content {");
        document.write("  display: none;");
        document.write("  position: absolute;");
        document.write("  background-color: #f9f9f9;");
        document.write("  min-width: 160px;");
        document.write("  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);");
        document.write("  z-index: 1;");
        document.write("}");
        document.write("");
        document.write(".dropdown-content a {");
        document.write("  float: none;");
        document.write("  color: black;");
        document.write("  padding: 12px 16px;");
        document.write("  text-decoration: none;");
        document.write("  display: block;");
        document.write("  text-align: left;");
        document.write("}");
        document.write("");
        document.write(".dropdown-content a:hover {");
        document.write("  background-color: #ddd;");
        document.write("}");
        document.write("");
        document.write(".dropdown:hover .dropdown-content {");
        document.write("  display: block;");
        document.write("");
        document.write("<\/style>");
        document.write("");